### PR TITLE
totem: switch to separate fork

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
I had to import > 60 commits to make some python modules work with Python 3.5, so it seems we need separate totem fork or find out why it behaves like crap after migration to clutter-gst.

**Comment by pyhalov** [comment]
Depends on #5564  and #5558

File: components/multimedia/totem/Makefile [hunk 1]
```diff
@@ -49,15 +55,33 @@ CONFIGURE_OPTIONS+= --disable-browser-plugins
...
+		dbusservice \
+		gromit \
+		im-status \
+		media-player-keys \
+		ontop \
+		opensubtitles \
+		properties \
+		pythonconsole \
+		samplepython \
+		sample-vala \
```
Comment (Mno-hime) [inline components/multimedia/totem/Makefile:71]: Build fails for me with:
```
make[5]: Entering directory '/export/home/newman/ws/oi-userland/components/multimedia/totem/build/amd64/src/plugins/sample-vala'
/usr/bin/intltool-merge /export/home/newman/ws/oi-userland/components/multimedia/totem/totem-b582e767ffb92fe4e57861a5e29f472ad025936f/po sample-vala.plugin.in sample-vala.plugin -d -u -c ../../../po/.intltool-merge-cache
  GEN      /export/home/newman/ws/oi-userland/components/multimedia/totem/totem-b582e767ffb92fe4e57861a5e29f472ad025936f/src/plugins/sample-vala/.gitignore
  VALAC    /export/home/newman/ws/oi-userland/components/multimedia/totem/totem-b582e767ffb92fe4e57861a5e29f472ad025936f/src/plugins/sample-vala/libsample_vala_la_vala.stamp
error: Package `Totem-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
```
Without `sample-vala` plugin builds fine.

**Comment by Mno-hime** [comment]
Fails to play a single video for me:
```
** Message: 08:58:56.736: Error: Can't play a text file without video or visualizations.
/jenkins/jobs/oi-userland/workspace/components/multimedia/gst-plugins-base/gst-plugins-base-0.10.36/gst/playback/gstplaysink.c(2215): gst_play_sink_reconfigure (): /GstPlayBin2:play/GstPlaySink:playsink0:
Have text pad but no video pad or visualizations
```
The stock one does fine.

**Comment by pyhalov** [comment]
I've tested updated version. With 64-bit gst-ffmpeg plays the same videos as before. 
@Mno-hime Are there any other issues to fix?
