### PR TITLE
python/numpy: add 1.26.4

### PR DESCRIPTION
**Pull request by iigs**
This is a dependency for inkscape.  I did not attempt to build this with python-integrate-project.

### CODE REVIEW

**Comment by ijones-gh** [comment]
iigs: Thank you for building numpy 1.26.4. I have failed to build numpy on OpenIndiana, due to compilation errors. Please see [numpy issues](https://github.com/numpy/numpy/issues/25366). Could you please document how you managed this so I can figure out what I was doing wrong and close the numpy bug. Thank you.

**Comment by iigs** [comment]
I started with Oracle's implementation of numpy. https://github.com/oracle/solaris-userland/tree/master/components/python/numpy .  But it didn't work.  This was back in January 2023.  I think I had numpy 1.23.4 building for both python 3.7 and 3.9, but I think I had issues with publishing.  Or maybe I had building issues for both python versions--I don't remember.  I had a single patch--the one for the 64-bit architecture to be detected (i86pc had to be added for cc_on_x64)--see my patch 01 .   I don't remember if this existed before or if I figured that out.

I notice that Peter Tribble updates numpy on Tribblix.  He has a patch:
https://github.com/tribblix/build/blob/master/patches/numpy-setup.patch

Some time later, I go back to numpy and worked on the 1.26.3 release.  I integrate Peter's patch.  Success in building.  I don't remember the problem, but I suspect that patch 02 fixes numpy Bug 25366.

Then there was a publish challenge.  By this point, I was regularly joining the OpenIndiana weekly coworking meeting.  I bring up the problem I was seeing. I don't remember how many publish issues I had fixed prior to the meeting, but I got help for any remaining (I recalled I got help how to handle the .pxd and .pyx -- I was clued in that I could grep for those strings in other .p5m files and add the necessary transform for numpy -- edit any paths as needed).  The publish issues were documented in the numpy-PYVER.p5m file in the three transform sections before the file list.

Looking over the Makefile in oi-userland, I don't recall if 
CFLAGS+= -D_GLIBCXX_NO_C99_ROUNDING_FUNCS is needed or if that part of my attempts to get things to work before patch 02.

Will you be working with the numpy folks to drop -D__STDC_VERSION__=0 for illumos builds?

**Comment by mtelka** [comment]
@iigs, I noticed an issue with the `numpy` package: it is missing the `_numpyconfig.h` file so software that wants to compile with numpy fails.  Could you please look at it?

This is the error from compilation of Cython tests:

```
distutils.errors.CompileError: command '/usr/gcc/13/bin/gcc' failed with exit code 1
Compiler output:
In file included from /usr/lib/python3.9/vendor-packages/numpy/core/include/numpy/npy_common.h:8,
                 from /usr/lib/python3.9/vendor-packages/numpy/core/include/numpy/ndarraytypes.h:4,
                 from /usr/lib/python3.9/vendor-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/lib/python3.9/vendor-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ufunc_ctuple.c:1487:
/usr/lib/python3.9/vendor-packages/numpy/core/include/numpy/numpyconfig.h:4:10: fatal error: _numpyconfig.h: No such file or directory
    4 | #include "_numpyconfig.h"
      |          ^~~~~~~~~~~~~~~~
```

Thank you.

**Comment by ijones-gh** [comment]
Thanks @iigs I've managed to compile and install numpy 1.26.4 with pip after removing "-D__STDC_VERSION__=0" from setup.py and meson.build. I'll add this to the numpy bug report and see if they have any additional insights. Thank you.

**Comment by iigs** [comment]
setup.py.mk needs to be fixed with PR #17227 .  numpy package needs to be rebuilt after PR is integrated.

**Comment by iigs** [comment]
Closed PR 17227 without merge.  reset COMPONENT_INSTALL_ARGS in numpy Makefile in PR #17231.  cython will probably need to be rebuilt after 17231 is integrated.
