### PR TITLE
Code::Blocks 20.03

### PR DESCRIPTION
**Pull request by hoewweken**
With my previous patch fpr wxwidgets-3 build publish and run are ok.
Code::Blocks 64Bit build with wxWidgest 3.1.5

### CODE REVIEW

**Comment by hoewweken** [comment]
without the compiler option -fpermissive we get this:

/home2/src/oi/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/src/app.cpp: In member function 'wxString CodeBlocksApp::GetAppPath() const':
/home2/src/oi/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/src/app.cpp:1152:48: error: invalid conversion from 'wxMBConv*' to 'std::size_t {aka long unsigned int}' [-fpermissive]
     base = wxString(getexecname(),wxConvCurrent);
                                                ^
In file included from /usr/include/wx-3.1/wx/memory.h:15:0,
                 from /usr/include/wx-3.1/wx/object.h:19,
                 from /usr/include/wx-3.1/wx/wx.h:15,
                 from /home2/src/oi/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/src/app.h:16,
                 from /home2/src/oi/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/src/app.cpp:11:
/usr/include/wx-3.1/wx/string.h:1188:3: note:   initializing argument 2 of 'wxString::wxString(const char*, std::size_t)'
   wxString(const char *psz, size_t nLength)
   ^~~~~~~~
make[4]: *** [Makefile:795: app.o] Error 1

**Comment by alarcher** [comment]
> without the compiler option -fpermissive we get this:
> 
> /home2/src/oi/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/src/app.cpp: In member function 'wxString CodeBlocksApp::GetAppPath() const': /home2/src/oi/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/src/app.cpp:1152:48: error: invalid conversion from 'wxMBConv*' to 'std::size_t {aka long unsigned int}' [-fpermissive] base = wxString(getexecname(),wxConvCurrent); ^ In file included from /usr/include/wx-3.1/wx/memory.h:15:0, from /usr/include/wx-3.1/wx/object.h:19, from /usr/include/wx-3.1/wx/wx.h:15, from /home2/src/oi/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/src/app.h:16, from /home2/src/oi/oi-userland/components/editor/codeblocks/codeblocks-20.03/src/src/app.cpp:11: /usr/include/wx-3.1/wx/string.h:1188:3: note: initializing argument 2 of 'wxString::wxString(const char*, std::size_t)' wxString(const char *psz, size_t nLength) ^~~~~~~~ make[4]: *** [Makefile:795: app.o] Error 1

The code seems to have changed quite a bit since 20.03, are you able to figure out if the solution is already integrated in last year's commits?

**Comment by hoewweken** [comment]
Hi!
After some search I found the subversion code tree. 
svn checkout svn://svn.code.sf.net/p/codeblocks/code/trunk

There is a somewhat similar patch in line 103 of watchesdlg.cpp:

   wxPGWindowList CreateControls(cb_unused wxPropertyGrid* propgrid,
                                  cb_unused wxPGProperty* property,
                                  cb_unused const wxPoint& pos,
                                  cb_unused const wxSize& sz) const override
    {
        **return wxPGWindowList(nullptr, nullptr);**
    }

If anyone knows about nightly tar balls, we could use a specific one by specifying a date or something in the Makefile, 
"subversion nightly" might not be something we want...

**Comment by hoewweken** [comment]
After some playing around with the 64bit build - i think there are some problems. For example i miss the "symbols" area in the left pane. I think i have to do more testing on the build result :-/

**Comment by hoewweken** [comment]
There is a branches subtree within svn, but watchesdlg.cpp is not patched there.
So either i will create patches for the 20.03 source tarball, or i will create a tarball  from trunk and use that.
I htink this can be closed now - or stay open for further communication around this topic.
Sorry for the turbulences here!

**Comment by hoewweken** [comment]
I will drop this.
A) Code::Blocks ist no more actively developed, and without the symbol tab not more useful than e.g. geany
B) I will switch to qtcreator. I have build Version 4.11.2 which is compatible with our QT 5.12. For qtcreator >= V5 QT >=5.14 is needed. My hope is that we'll get QT 6 ported to OI later this year, with that we could deliver qtcreator 6....
